
# DINOv3 ViT-7B with a shallow head configuration

seed: 42

model:
  name: 'dinov3_vit7b16'
  weights: 'model/dinov3_vit7b16.pth'
  num_classes: 1
  head_channels: [256, 128] # Shallow head

training:
  epochs: 25
  batch_size: 1 # Minimal batch size for this massive model
  optimizer:
    lr0: 0.0001

dataset:
  train_images: '../data/images/train'
  train_masks: '../data/gt/train'
  val_images: '../data/images/val'
  val_masks: '../data/gt/val'
  test_images: '../data/images/test'
  test_masks: '../data/gt/test'
  reject_images: '../data/reject'

output:
  save_dir: 'output'
  run_name: 'dinov3_vit7b16_shallow_head_e25'

benchmarking:
  threshold: 0.5
